name: ba_museum_rag_system_test
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - expat=2.7.1=h313beb8_0
  - faiss=1.9.0=py310h2dd55c0_0_cpu
  - faiss-cpu=1.9.0=hd610c6a_0
  - libblas=3.9.0=35_h10e41b3_openblas
  - libcblas=3.9.0=35_hb3479ef_openblas
  - libcxx=20.1.8=h8869778_0
  - libfaiss=1.9.0=h682f5e0_0_cpu
  - libffi=3.4.4=hca03da5_1
  - libgfortran=15.1.0=hfdf1602_1
  - libgfortran5=15.1.0=hb74de2c_1
  - liblapack=3.9.0=35_hc9a63f6_openblas
  - libopenblas=0.3.30=openmp_h60d53f8_2
  - libsqlite=3.46.0=hfb93653_0
  - libzlib=1.2.13=hfb2fe0b_6
  - llvm-openmp=20.1.8=hbb9b287_2
  - ncurses=6.5=hee39554_0
  - openai=1.106.1=pyhd8ed1ab_0
  - openssl=3.5.2=he92f556_0
  - pip=25.2=pyhc872135_0
  - python=3.10.14=h2469fbe_0_cpython
  - python_abi=3.10=8_cp310
  - readline=8.3=h0b18652_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.15=hcd8a7d5_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wheel=0.45.1=py310hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.2.13=hfb2fe0b_6
  - pip:
      - accelerate==1.10.1
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - aiosqlite==0.21.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - backoff==2.2.1
      - banks==2.2.0
      - beautifulsoup4==4.13.5
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - click==8.2.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cryptography==45.0.7
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dirtyjson==1.0.8
      - distro==1.9.0
      - effdet==0.4.1
      - emoji==2.14.1
      - exceptiongroup==1.3.0
      - fastapi==0.116.1
      - filelock==3.19.1
      - filetype==1.2.0
      - flatbuffers==25.2.10
      - fonttools==4.59.2
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-cloud-vision==3.10.2
      - googleapis-common-protos==1.70.0
      - greenlet==3.2.4
      - griffe==1.14.0
      - grpcio==1.74.0
      - grpcio-status==1.74.0
      - h11==0.16.0
      - hf-xet==1.1.9
      - html5lib==1.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - humanfriendly==10.0
      - idna==3.10
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.9
      - langdetect==1.0.9
      - llama-cloud==0.1.35
      - llama-cloud-services==0.6.54
      - llama-index==0.13.5
      - llama-index-cli==0.5.0
      - llama-index-core==0.13.5
      - llama-index-embeddings-huggingface==0.6.0
      - llama-index-embeddings-openai==0.5.0
      - llama-index-indices-managed-llama-cloud==0.9.3
      - llama-index-instrumentation==0.4.0
      - llama-index-llms-openai==0.5.4
      - llama-index-readers-file==0.5.3
      - llama-index-readers-llama-parse==0.5.0
      - llama-index-vector-stores-faiss==0.5.0
      - llama-index-workflows==1.3.0
      - llama-parse==0.6.54
      - lxml==6.0.1
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.6
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - multidict==6.6.4
      - mypy-extensions==1.1.0
      - narwhals==2.3.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==1.26.4
      - olefile==0.47
      - ollama==0.5.3
      - omegaconf==2.3.0
      - onnx==1.19.0
      - onnxruntime==1.22.1
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pandas==2.2.3
      - pdf2image==1.17.0
      - pdfminer-six==20250506
      - pi-heif==1.1.0
      - pikepdf==9.10.2
      - pillow==11.3.0
      - platformdirs==4.4.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==6.32.0
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.10
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pyparsing==3.2.3
      - pypdf==6.0.0
      - pypdfium2==4.30.0
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - python-dotenv==1.1.1
      - python-iso639==2025.2.18
      - python-magic==0.4.27
      - python-multipart==0.0.20
      - python-oxmsg==0.0.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - rapidfuzz==3.14.0
      - referencing==0.36.2
      - regex==2025.9.1
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rpds-py==0.27.1
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - sentence-transformers==2.6.1
      - setuptools==80.9.0
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.43
      - starlette==0.47.3
      - streamlit==1.49.1
      - striprtf==0.0.26
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.11.0
      - timm==1.0.19
      - tokenizers==0.15.2
      - toml==0.10.2
      - torch==2.8.0
      - torchvision==0.23.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - transformers==4.36.2
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - unstructured==0.18.14
      - unstructured-client==0.42.3
      - unstructured-inference==1.0.5
      - unstructured-pytesseract==0.3.15
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - webencodings==0.5.1
      - wrapt==1.17.3
      - yarl==1.20.1
prefix: /opt/homebrew/Caskroom/miniconda/base/envs/ba_museum_rag_system
